import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

public class StringUtils {

    String decodedString;

    String decodeFromString(String stringForDecode) {

        Map<String, String> specialChars = new HashMap<>();

        // NAME //

        specialChars.put("&nbsp;", " ");
        specialChars.put("&amp;", "&");
        specialChars.put("&pound;", "£");
        specialChars.put("&euro;", "€");
        specialChars.put("&para;", "¶");
        specialChars.put("&sect;", "§");
        specialChars.put("&reg;", "®");
        specialChars.put("&copy;", "©");
        specialChars.put("&trade;", "™");
        specialChars.put("&deg;", "°");
        specialChars.put("&plusmn;", "±");
        specialChars.put("&frac14", "¼");
        specialChars.put("&frac12;", "½");
        specialChars.put("&frac34;", "¾");
        specialChars.put("&times;", "×");
        specialChars.put("&divide;", "÷");
        specialChars.put("&fnof;", "ƒ");
        specialChars.put("&Alpha;", "Α");
        specialChars.put("&Beta;", "Β");
        specialChars.put("&Gamma;", "Γ");
        specialChars.put("&Delta;", "Δ");
        specialChars.put("&Epsilon;", "Ε");
        specialChars.put("&Zeta;", "Ζ");
        specialChars.put("&Eta;", "Η");
        specialChars.put("&Theta;", "Θ");
        specialChars.put("&lota;", "Ι");
        specialChars.put("&Kappa;", "\tΚ");
        specialChars.put("&Lambda;", "Λ");
        specialChars.put("&Mu;", "Μ");
        specialChars.put("&Nu;", "Ν");
        specialChars.put("&Xi;", "Ξ");
        specialChars.put("&Omicron;", "Ο");
        specialChars.put("&Pi;", "Π");
        specialChars.put("&Rho;", "Ρ");
        specialChars.put("&Sigma;", "Σ");
        specialChars.put("&Tau;", "Τ");
        specialChars.put("&Upsilon;", "Υ");
        specialChars.put("&Phi;", "Φ");
        specialChars.put("&Chi;", "Χ");
        specialChars.put("&Psi;", "Ψ");
        specialChars.put("&Omega;", "Ω");
        specialChars.put("&alpha;", "α");
        specialChars.put("&beta;", "β");
        specialChars.put("&gamma;", "γ");
        specialChars.put("&delta;", "δ");
        specialChars.put("&epsilon;", "\tε");
        specialChars.put("&zeta;", "ζ");
        specialChars.put("&eta;", "η");
        specialChars.put("&theta;", "θ");
        specialChars.put("&iota;", "ι");
        specialChars.put("&kappa;", "κ");
        specialChars.put("&lambda;", "λ");
        specialChars.put("&mu;", "μ");
        specialChars.put("&nu;", "ν");
        specialChars.put("&xi;", "ξ");
        specialChars.put("&omicron;", "ο");
        specialChars.put("&pi;", "π");
        specialChars.put("&rho;", "ρ");
        specialChars.put("&sigmaf;", "ς");
        specialChars.put("&sigma;", "σ");
        specialChars.put("&tau;", "τ");
        specialChars.put("&upsilon;", "υ");
        specialChars.put("&phi;", "φ");
        specialChars.put("&chi;", "χ");
        specialChars.put("&psi;", "ψ");
        specialChars.put("&omega;", "ω");
        specialChars.put("&larr;", "←");
        specialChars.put("&uarr;", "↑");
        specialChars.put("&rarr;", "→");
        specialChars.put("&darr;", "↓");
        specialChars.put("&harr;", "↔");
        specialChars.put("&spades;", "♠");
        specialChars.put("&clubs;", "♣");
        specialChars.put("&hearts;", "♥");
        specialChars.put("&diams;", "♦");
        specialChars.put("&quot;", "\"");
        specialChars.put("&lt;", "<");
        specialChars.put("&gt;", ">");
        specialChars.put("&hellip;", "…");
        specialChars.put("&prime;", "′");
        specialChars.put("&Prime;", "″");
        specialChars.put("&ndash;", "–");
        specialChars.put("&mdash;", "—");
        specialChars.put("&lsquo;", "‘");
        specialChars.put("&rsquo;", "’");
        specialChars.put("&sbquo;", "‚");
        specialChars.put("&ldquo;", "“");
        specialChars.put("&rdquo;", "”");
        specialChars.put("&bdquo;", "„");
        specialChars.put("&laquo;", "«");
        specialChars.put("&raquo;", "»");

        // CODE //

        specialChars.put("&#160;", " ");
        specialChars.put("&#38;", "&");
        specialChars.put("&#163;", "£");
        specialChars.put("&#8364;", "€");
        specialChars.put("&#182;", "¶");
        specialChars.put("&#167;", "§");
        specialChars.put("&#174;", "®");
        specialChars.put("&#169;", "©");
        specialChars.put("&#8482;", "™");
        specialChars.put("&#176;", "°");
        specialChars.put("&#177;", "±");
        specialChars.put("&#188;", "¼");
        specialChars.put("&#189;", "½");
        specialChars.put("&#190;", "¾");
        specialChars.put("&#215;", "×");
        specialChars.put("&#247;", "÷");
        specialChars.put("&#402;", "ƒ");
        specialChars.put("&#913;", "Α");
        specialChars.put("&#914;", "Β");
        specialChars.put("&#915;", "Γ");
        specialChars.put("&#916;", "Δ");
        specialChars.put("&#917;", "Ε");
        specialChars.put("&#918;", "Ζ");
        specialChars.put("&#919;", "Η");
        specialChars.put("&#920;", "Θ");
        specialChars.put("&#921;", "Ι");
        specialChars.put("&#922;", "\tΚ");
        specialChars.put("&#923;", "Λ");
        specialChars.put("&#924;", "Μ");
        specialChars.put("&#925;", "Ν");
        specialChars.put("&#926;", "Ξ");
        specialChars.put("&#927;", "Ο");
        specialChars.put("&#928;", "Π");
        specialChars.put("&#929;", "Ρ");
        specialChars.put("&#931;", "Σ");
        specialChars.put("&#932;", "Τ");
        specialChars.put("&#933;", "Υ");
        specialChars.put("&#934;", "Φ");
        specialChars.put("&#935;", "Χ");
        specialChars.put("&#936;", "Ψ");
        specialChars.put("&#937;", "Ω");
        specialChars.put("&#945;", "α");
        specialChars.put("&#946;", "β");
        specialChars.put("&#947;", "γ");
        specialChars.put("&#948;", "δ");
        specialChars.put("&#949;", "\tε");
        specialChars.put("&#950;", "ζ");
        specialChars.put("&#951;", "η");
        specialChars.put("&#952;", "θ");
        specialChars.put("&#953;", "ι");
        specialChars.put("&#954;", "κ");
        specialChars.put("&#955;", "λ");
        specialChars.put("&#956;", "μ");
        specialChars.put("&#957;", "ν");
        specialChars.put("&#958;", "ξ");
        specialChars.put("&#959;", "ο");
        specialChars.put("&#960;", "π");
        specialChars.put("&#961;", "ρ");
        specialChars.put("&#962;", "ς");
        specialChars.put("&#963;", "σ");
        specialChars.put("&#964;", "τ");
        specialChars.put("&#965;", "υ");
        specialChars.put("&#966;", "φ");
        specialChars.put("&#967;", "χ");
        specialChars.put("&#968;", "ψ");
        specialChars.put("&#969;", "ω");
        specialChars.put("&#8592;", "←");
        specialChars.put("&#8593;", "↑");
        specialChars.put("&#8594;", "→");
        specialChars.put("&#8595;", "↓");
        specialChars.put("&#8596;", "↔");
        specialChars.put("&#9824;", "♠");
        specialChars.put("&#9827;", "♣");
        specialChars.put("&#9829;", "♥");
        specialChars.put("&#9830;", "♦");
        specialChars.put("&#34;", "\"");
        specialChars.put("&#60;", "<");
        specialChars.put("&#62;", ">");
        specialChars.put("&#8230;", "…");
        specialChars.put("&#8242;", "′");
        specialChars.put("&#8243;", "″");
        specialChars.put("&#8211;", "–");
        specialChars.put("&#8212;", "—");
        specialChars.put("&#8216;", "‘");
        specialChars.put("&#8217;", "’");
        specialChars.put("&#8218;", "‚");
        specialChars.put("&#8220;", "“");
        specialChars.put("&#8221;", "”");
        specialChars.put("&#8222;", "„");
        specialChars.put("&#171;", "«");
        specialChars.put("&#187;", "»");

        for(Map.Entry<String, String> entry : specialChars.entrySet()){
            decodedString = stringForDecode.replace(entry.getKey(), entry.getValue());
            stringForDecode = decodedString;
        }
        return decodedString;
    }
}